name: Ping Render Server Every 13 Minutes

on:
  schedule:
    - cron: '*/13 * * * *'

jobs:
  ping-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run ping script
        run: python ping.py
